### ISSUE TITLE
GIS.lab web wfs getcapabilities request does not work

### ISSUE THREAD

**Issue by jachym** [gislab-npo/gislab-web#17]
When initializing WFS configuration, something like 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/OWSLib-0.9.dev0-py2.7.egg/owslib/wfs.py", line 36, in WebFeatureService
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/OWSLib-0.9.dev0-py2.7.egg/owslib/feature/wfs100.py", line 70, in __new__
    obj.__init__(url, version, xml, parse_remote_metadata, timeout)
  File "/usr/local/lib/python2.7/dist-packages/OWSLib-0.9.dev0-py2.7.egg/owslib/feature/wfs100.py", line 92, in __init__
    self._buildMetadata(parse_remote_metadata)
  File "/usr/local/lib/python2.7/dist-packages/OWSLib-0.9.dev0-py2.7.egg/owslib/feature/wfs100.py", line 102, in _buildMetadata
    self.provider=ServiceProvider(serviceelem)   
  File "/usr/local/lib/python2.7/dist-packages/OWSLib-0.9.dev0-py2.7.egg/owslib/feature/wfs100.py", line 281, in __init__
    self.keywords = extract_xml_list(self._root.find(nspath('Keywords')))
  File "/usr/local/lib/python2.7/dist-packages/OWSLib-0.9.dev0-py2.7.egg/owslib/util.py", line 535, in extract_xml_list
    keywords = [re.split(r'[\n\r]+',f.text) for f in elements if f.text]
TypeError: 'NoneType' object is not iterable
```
will appear. This seems to be do to QGIS invalid response as reported https://hub.qgis.org/issues/13037

Workaround prepared, for owslib https://github.com/jachym/OWSLib/commit/679668abb1efef3b02f0908e3c178598db4ab557#diff-ee406d4961a0fd834c9da10edd752863L537 could be applied temporary in GIS.lab too

**Comment by jachym** [comment]
this should be ok, right? btw owslib accepted the patch, it should be there in next release
